### ISSUE TITLE
after install and try to run it I have received this error: Parameter 'expression' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by garikKalash** [Romakita/ts-json-properties#2]
![screenshot 37](https://cloud.githubusercontent.com/assets/15331012/26058901/d8811af6-3990-11e7-90c4-7821346ef699.png)

**Comment by Romakita** [comment]
Hi @garikKalash,

Try to remove `src/value` after `ts-json-properties` in your import. It's the problem when you use the Typescript file as a source from another module. My module doesn't use the impliciteAny compilation option ;)

But I see, you want to use this module with an Angular project. I think's that didn't work, because TsJsonProperties use the Node.js FileSystem to work.  Isn't a front module ^^.

See you
